version: '3.8'

services:
  mediawiki_database:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: mediawiki_db
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
      
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    ports:
      - "8080:80"
    environment:
      MEDIAWIKI_DB_HOST: mediawiki_database
      MEDIAWIKI_DB_USER: wikiuser
      MEDIAWIKI_DB_PASSWORD: P@ssw0rd
      MEDIAWIKI_DB_NAME: mediawiki
    depends_on:
      - mediawiki_database
    volumes:
      - images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    restart: unless-stopped

volumes:
  database:
  images:
