version: "3.9"

services:
  wikijs-db:
    image: postgres:15
    container_name: wikijs-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs123
    volumes:
      - wikijs_db:/var/lib/postgresql/data

  wikijs:
    image: requarks/wiki:latest
    container_name: wikijs
    restart: unless-stopped
    depends_on:
      - wikijs-db
    ports:
      - "8080:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs123
      DB_NAME: wiki
    volumes:
      - wikijs_data:/wiki/data

  countly-db:
    image: mongo:5
    container_name: countly-db
    restart: always
    volumes:
      - countly_db:/data/db

  countly:
    image: countly/countly-server
    container_name: countly
    restart: always
    depends_on:
      - countly-db
    ports:
      - "9000:80"
    environment:
      COUNTLY_MONGODB_HOST: countly-db
      COUNTLY_MONGODB_PORT: 27017

      # Countly admin login
      COUNTLY_ADMIN_EMAIL: admin@countly.local
      COUNTLY_ADMIN_USERNAME: countlyadmin
      COUNTLY_ADMIN_PASSWORD: CountlyPass123!

volumes:
  wikijs_db:
  wikijs_data:
  countly_db: